title: Equilaterus.Vortex
description: Vortex is a .Net Standard framework focused on Functional Programming.
theme: jekyll-theme-tactile
show_downloads: true
github:
  zip_url: https://www.nuget.org/packages/Equilaterus.Vortex
