version: 0.3.3.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '0.3.3'
  package_version: '0.3.3'
  assembly_version: '0.3.3'
  file_version: '0.3.3'
  informational_version: '0.3.3'
before_build:
- cmd: nuget restore
build:
  project: Equilaterus.Vortex.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: WfQbHXHq3gu23bo1V3NY20wjg0pmUHv4C7GNbUqM6hX5X0TQ3JXDasLcOj7CPkc0
  on:
    branch: release