version: 1.0.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '1.0.0'
  package_version: '1.0.0'
  assembly_version: '1.0.0'
  file_version: '1.0.0'
  informational_version: '1.0.0'
before_build:
- cmd: nuget restore
build:
  project: Equilaterus.Vortex.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: gDjYdO8bhtrCzOIQ4v8Dz2aAr3CD9gkvu2L0yJ8r8oMAzYzjLZmRIb0b6d8kaKxb
  on:
    branch: release